(function(){
'use strict';
const $=id=>document.getElementById(id),qa=(s,r=document)=>[...r.querySelectorAll(s)];
const rad=d=>d*Math.PI/180,deg=r=>r*180/Math.PI,norm=a=>((a%360)+360)%360;
const mean=a=>{const v=a.filter(Number.isFinite);return v.length?v.reduce((x,y)=>x+y,0)/v.length:null};
const sd=a=>{const v=a.filter(Number.isFinite),m=mean(v);return v.length>1?Math.sqrt(v.reduce((s,x)=>s+(x-m)**2,0)/(v.length-1)):null};
const circMean=a=>{const v=a.filter(Number.isFinite);if(!v.length)return null;return norm(deg(Math.atan2(mean(v.map(x=>Math.sin(rad(x)))),mean(v.map(x=>Math.cos(rad(x)))))))};
const circSd=a=>{const v=a.filter(Number.isFinite);if(v.length<2)return null;const x=mean(v.map(a=>Math.cos(rad(a)))),y=mean(v.map(a=>Math.sin(rad(a)))),R=Math.min(1,Math.hypot(x,y));return deg(Math.sqrt(Math.max(0,-2*Math.log(Math.max(R,1e-8)))))};
const dir8=h=>!Number.isFinite(h)?'—':['N','NE','E','SE','S','SW','W','NW'][Math.round(norm(h)/45)%8];
const S={heading:null,tilt:null,beta:null,gamma:null,absolute:false,source:'—',samples:[],levelSamples:[],frozen:false,reference:'mag',gps:null};
function rotationNormal(alpha,beta,gamma){const a=rad(alpha||0),b=rad(beta||0),g=rad(gamma||0),ca=Math.cos(a),sa=Math.sin(a),cb=Math.cos(b),sb=Math.sin(b),cg=Math.cos(g),sg=Math.sin(g);return{x:cg*sa*sb+ca*sg,y:sa*sg-ca*cg*sb,z:cb*cg}}
function planeTilt(alpha,beta,gamma){let n=rotationNormal(alpha,beta,gamma);if(n.z<0)n={x:-n.x,y:-n.y,z:-n.z};return{tilt:deg(Math.atan2(Math.hypot(n.x,n.y),Math.abs(n.z))),nx:n.x,ny:n.y,nz:n.z}}
function flatHeading(alpha){return norm(360-alpha)}
function compassHeading(alpha,beta,gamma){if(![alpha,beta,gamma].every(Number.isFinite))return null;const x=rad(beta),y=rad(gamma),z=rad(alpha),cX=Math.cos(x),cY=Math.cos(y),cZ=Math.cos(z),sX=Math.sin(x),sY=Math.sin(y),sZ=Math.sin(z),Vx=-cZ*sY-sZ*sX*cY,Vy=-sZ*sY+cZ*sX*cY;if(Math.abs(Vx)<1e-12&&Math.abs(Vy)<1e-12)return flatHeading(alpha);return norm(deg(Math.atan2(Vx,Vy)))}
function headingFromEvent(e){if(Number.isFinite(e.webkitCompassHeading))return{heading:norm(e.webkitCompassHeading),absolute:true,source:'webkitCompassHeading'};const a=Number(e.alpha),b=Number(e.beta),g=Number(e.gamma);if(!Number.isFinite(a))return{heading:null,absolute:false,source:'none'};const tilt=planeTilt(a,b,g).tilt;return{heading:tilt<18?flatHeading(a):compassHeading(a,b,g),absolute:!!e.absolute,source:e.absolute?'deviceorientation_absolute':'deviceorientation_relative'}}
function decl(){const raw=$('ar6Decl')?.value?.trim();if(raw==='')return null;const v=Number(raw);return Number.isFinite(v)?v:null}
function trueHeading(){const d=decl();return Number.isFinite(S.heading)&&Number.isFinite(d)?norm(S.heading+d):null}
function qCompass(){const d=circSd(S.samples.slice(-10));if(S.samples.length<5)return{cls:'wait',label:'Aguardando leituras',disp:d};if(!S.absolute)return{cls:'wait',label:'Referência relativa',disp:d};if(Number.isFinite(d)&&d<=3)return{cls:'',label:'Medição estável',disp:d};if(Number.isFinite(d)&&d<=8)return{cls:'wait',label:'Estabilidade moderada',disp:d};return{cls:'bad',label:'Medição instável',disp:d}}
function qLevel(){const d=sd(S.levelSamples.slice(-10));if(S.levelSamples.length<5)return{cls:'wait',label:'Aguardando leituras',disp:d};if(Number.isFinite(d)&&d<=.6)return{cls:'',label:'Nível estável',disp:d};if(Number.isFinite(d)&&d<=2)return{cls:'wait',label:'Estabilidade moderada',disp:d};return{cls:'bad',label:'Leitura instável',disp:d}}
function degreeLabels(){return [0,30,60,90,120,150,180,210,240,270,300,330].map(a=>`<span class="ar6-degree" style="--a:${a}deg">${a}</span>`).join('')}
function compassHTML(){return `<div class="modal-box ita-sensor-modal"><header class="ar6-head"><div><div class="kicker">ITA ARANDU MS · BANCADA DIGITAL</div><h2>Bússola Geológica</h2></div><button class="ar6-close" data-close="bussolaAranduModal" aria-label="Fechar">×</button></header><nav class="ar6-tabs"><button class="active" data-ar6-go="measure">⌖ Medir</button><button data-ar6-go="data">☷ Dados</button><button data-ar6-go="analysis">▥ Análise</button><button data-ar6-go="science">ⓘ Ciência</button></nav><div class="ar6-body">
<section class="ar6-reference"><div class="ar6-ref nm"><strong>Nm</strong><small>Norte magnético</small></div><div class="ar6-delta" id="ar6DeltaTop">δ não definida<small>declinação local</small></div><div class="ar6-ref ng"><strong>Ng</strong><small>Norte geográfico</small></div></section>
<section class="ar6-dial-wrap" id="ar6Measure"><div class="ar6-dial"><div class="ar6-ticks"></div>${degreeLabels()}<span class="ar6-cardinal ar6-n">N</span><span class="ar6-cardinal ar6-e">E</span><span class="ar6-cardinal ar6-s">S</span><span class="ar6-cardinal ar6-w">W</span><span class="ar6-subcard ar6-ne">NE</span><span class="ar6-subcard ar6-nw">NW</span><span class="ar6-subcard ar6-se">SE</span><span class="ar6-subcard ar6-sw">SW</span><div class="ar6-star"></div><div class="ar6-geo-needle" id="ar6GeoNeedle"></div><div class="ar6-needle" id="ar6Needle"></div><div class="ar6-center"></div></div></section>
<div class="ar6-mode"><button class="active" data-ar6-ref="mag">Magnético · Nm</button><button data-ar6-ref="geo">Geográfico · Ng</button></div>
<section class="ar6-card"><div class="ar6-readings"><div class="ar6-reading primary"><small id="ar6AzLabel">Azimute Nm</small><strong id="ar6Az">—</strong><em id="ar6Dir">—</em></div><div class="ar6-reading"><small>Mergulho</small><strong id="ar6Dip">—</strong><em>tela</em></div><div class="ar6-reading good"><small>Dispersão</small><strong id="ar6Disp">—</strong><em id="ar6DispLabel">—</em></div></div><div class="ar6-quality wait" id="ar6Quality">● Aguardando sensores</div></section>
<div class="ar6-actions"><button class="ar6-btn" id="ar6Lock">▣ Travar</button><button class="ar6-btn" id="ar6Calibrate">⌖ Calibrar</button><button class="ar6-btn" id="ar6More">••• Mais</button></div><button class="ar6-btn primary ar6-save" id="ar6Save">▣ Salvar medição</button>
<details class="ar6-details" id="ar6Data"><summary>Estação geológica <span class="ar6-mini-status" id="ar6StationSummary">sem classificação</span></summary><div class="inside ar6-grid2"><div class="ar6-field"><span>Tipo de elemento</span><select id="ar6Element"><option>Plano</option><option>Fratura</option><option>Falha</option><option>Foliação</option><option>Veio</option><option>Contato</option><option>Lineação</option><option>Outro</option></select></div><div class="ar6-field"><span>Estrutura</span><input id="ar6Structure" placeholder="Ex. fratura conjugada"></div><div class="ar6-field" style="grid-column:1/-1"><span>Observação</span><textarea id="ar6Obs" rows="3" placeholder="Descrição geológica breve"></textarea></div></div></details>
<details class="ar6-details"><summary>Foto e observação</summary><div class="inside"><button class="ar6-btn" id="ar6Photo">📷 Abrir GeoCâmera</button><div class="ar6-help">A fotografia deve permanecer vinculada à estação e à medição. O rumo da foto não substitui a atitude estrutural medida.</div></div></details>
<details class="ar6-details" id="ar6Analysis"><summary>Análise e integração <span class="ar6-mini-status" id="ar6SampleCount">0 leituras</span></summary><div class="inside"><div class="ar6-grid2"><button class="ar6-btn" id="ar6Stereo">◯ Rede Estereográfica</button><button class="ar6-btn" id="ar6Rose">✺ Diagrama de Rosas</button></div><div class="ar6-help" id="ar6AnalysisText">Ative os sensores para iniciar o controle de estabilidade.</div><div class="ar6-recent" id="ar6Recent"></div></div></details>
<details class="ar6-details"><summary>Dados e localização <span class="ar6-mini-status" id="ar6GpsShort">GPS não capturado</span></summary><div class="inside"><button class="ar6-btn" id="ar6Gps">⌖ Minha localização</button><div class="ar6-help" id="ar6GpsText">Latitude, longitude, altitude e precisão serão registradas somente quando o usuário solicitar.</div></div></details>
<details class="ar6-details" id="ar6Science"><summary>Ajuda e Ciência</summary><div class="inside"><div class="ar6-help"><b>Norte magnético e norte geográfico</b><br>A bússola do dispositivo responde ao campo magnético local. A declinação δ é o ângulo entre norte magnético e norte verdadeiro e varia com lugar e tempo. Quando δ é conhecida, ITA ARANDU usa Ng = Nm + δ. Valores a leste são positivos e a oeste negativos.<br><br><b>Importante</b><br>O aplicativo não inventa a declinação. Sem valor informado, Ng permanece indisponível. Para trabalho documentado, registre a fonte e a data da declinação. O WMM2025 é o modelo geomagnético global vigente para 2025–2029.</div><div class="ar6-grid2"><div class="ar6-field"><span>Declinação local δ °</span><input id="ar6Decl" type="number" step="0.1" placeholder="Ex. -18.4 para oeste"></div><div class="ar6-field"><span>Fonte da declinação</span><input id="ar6DeclSource" placeholder="Ex. NOAA WMM2025"></div></div><a class="ar6-btn" style="text-align:center;text-decoration:none" href="https://www.ngdc.noaa.gov/geomag/calculators/magcalc.shtml" target="_blank" rel="noopener">Consultar calculador oficial NOAA</a></div></details>
<div class="ar6-mini-status" id="bussolaStatus">Ative os sensores por gesto explícito.</div></div></div>`}
function levelHTML(){return `<div class="modal-box ita-sensor-modal"><header class="ar6-head"><div><div class="kicker">ITA ARANDU MS · BANCADA DIGITAL</div><h2>Nível Digital</h2></div><button class="ar6-close" data-close="nivelAranduModal">×</button></header><nav class="ar6-tabs"><button class="active">⊥ Medir</button><button data-level-go="science">ⓘ Ciência</button></nav><div class="ar6-body"><div class="ar6-level-stage"><div class="ar6-bubble" id="ar6Bubble"></div></div><section class="ar6-card"><div class="ar6-readings"><div class="ar6-reading"><small>Inclinação</small><strong id="ar6Tilt">—</strong><em>plano da tela</em></div><div class="ar6-reading"><small>β</small><strong id="ar6Beta">—</strong><em>frente–trás</em></div><div class="ar6-reading good"><small>γ</small><strong id="ar6Gamma">—</strong><em>lateral</em></div></div><div class="ar6-quality wait" id="ar6LevelQuality">● Aguardando sensores</div></section><div class="ar6-actions"><button class="ar6-btn primary" id="ar6LevelStart">Ativar sensores</button><button class="ar6-btn" id="ar6LevelZero">Zerar</button><button class="ar6-btn" id="ar6LevelSave">Salvar</button></div><details class="ar6-details" id="ar6LevelScience"><summary>Ajuda e Ciência</summary><div class="inside"><div class="ar6-help"><b>Nível assistido</b><br>A leitura usa a orientação do dispositivo e representa a inclinação do plano da tela. Não substitui instrumento topográfico nem deve ser tratada como medida absoluta sem calibração e controle de repetibilidade. Apoie o aparelho de forma estável e repita as leituras.</div></div></details><div class="ar6-mini-status" id="nivelStatus">Ative os sensores por gesto explícito.</div></div></div>`}
function replaceModals(){const b=$('bussolaAranduModal'),n=$('nivelAranduModal');if(b)b.innerHTML=compassHTML();if(n)n.innerHTML=levelHTML();qa('#ferramentasModal [data-tool-action="bussola"],#ferramentasModal [data-tool-action="nivel"]').forEach(x=>x.classList.add('primary'))}
function open(id){const m=$(id);if(m){m.classList.add('open');m.setAttribute('aria-hidden','false');document.body.classList.add('modal-open')}}
function close(id){const m=$(id);if(m){m.classList.remove('open');m.setAttribute('aria-hidden','true')}}
function onOrientation(e){if(S.frozen)return;const h=headingFromEvent(e),lv=planeTilt(Number(e.alpha),Number(e.beta),Number(e.gamma));S.heading=h.heading;S.absolute=h.absolute;S.source=h.source;S.tilt=lv.tilt;S.beta=Number(e.beta);S.gamma=Number(e.gamma);if(Number.isFinite(S.heading)){S.samples.push(S.heading);if(S.samples.length>60)S.samples.shift()}if(Number.isFinite(S.tilt)){S.levelSamples.push(S.tilt);if(S.levelSamples.length>60)S.levelSamples.shift()}renderCompass();renderLevel(lv)}
async function startSensors(){try{if(typeof DeviceOrientationEvent==='undefined')throw new Error('DeviceOrientationEvent indisponível');if(typeof DeviceOrientationEvent.requestPermission==='function'){const p=await DeviceOrientationEvent.requestPermission();if(p!=='granted')throw new Error('permissão não concedida')}window.removeEventListener('deviceorientationabsolute',onOrientation,true);window.removeEventListener('deviceorientation',onOrientation,true);window.addEventListener('deviceorientationabsolute',onOrientation,true);window.addEventListener('deviceorientation',onOrientation,true);$('bussolaStatus')&&($('bussolaStatus').textContent='Sensores ativos. Afaste o telefone de metal, ímãs, cabos e alto-falantes.');$('nivelStatus')&&($('nivelStatus').textContent='Sensores ativos. Apoie o dispositivo de forma estável.')}catch(err){$('bussolaStatus')&&($('bussolaStatus').textContent='Sensores indisponíveis · '+err.message);$('nivelStatus')&&($('nivelStatus').textContent='Sensores indisponíveis · '+err.message)}}
function renderCompass(){if(!$('ar6Az'))return;const q=qCompass(),mag=S.heading,geo=trueHeading(),shown=S.reference==='geo'?geo:mag;$('ar6Az').textContent=Number.isFinite(shown)?shown.toFixed(1)+'°':'—';$('ar6Dir').textContent=dir8(shown);$('ar6AzLabel').textContent=S.reference==='geo'?'Azimute Ng':'Azimute Nm';$('ar6Dip').textContent=Number.isFinite(S.tilt)?S.tilt.toFixed(1)+'°':'—';$('ar6Disp').textContent=Number.isFinite(q.disp)?q.disp.toFixed(1)+'°':'—';$('ar6DispLabel').textContent=Number.isFinite(q.disp)?(q.disp<=3?'Boa':q.disp<=8?'Regular':'Alta'):'—';$('ar6Quality').className='ar6-quality '+q.cls;$('ar6Quality').textContent='● '+q.label+' · '+(S.absolute?'referência absoluta':'referência relativa');$('ar6SampleCount').textContent=Math.min(10,S.samples.length)+' / 10 leituras';$('ar6AnalysisText').textContent=`Fonte ${S.source} · dispersão ${Number.isFinite(q.disp)?q.disp.toFixed(2)+'°':'—'} · ${q.label}. A estabilidade não prova ausência de anomalia magnética local.`;if(Number.isFinite(mag))$('ar6Needle').style.transform=`translate(-50%,-100%) rotate(${-mag}deg)`;const g=$('ar6GeoNeedle');if(g){if(Number.isFinite(geo)){g.style.display='block';g.style.transform=`translate(-50%,-100%) rotate(${-geo}deg)`}else g.style.display='none'}const d=decl();$('ar6DeltaTop').innerHTML=Number.isFinite(d)?`δ ${Math.abs(d).toFixed(1)}° ${d<0?'W':'E'}<small>declinação local</small>`:'δ não definida<small>declinação local</small>'}
function renderLevel(lv){if(!$('ar6Tilt'))return;const q=qLevel();$('ar6Tilt').textContent=Number.isFinite(S.tilt)?S.tilt.toFixed(1)+'°':'—';$('ar6Beta').textContent=Number.isFinite(S.beta)?S.beta.toFixed(1)+'°':'—';$('ar6Gamma').textContent=Number.isFinite(S.gamma)?S.gamma.toFixed(1)+'°':'—';$('ar6LevelQuality').className='ar6-quality '+q.cls;$('ar6LevelQuality').textContent='● '+q.label+(Number.isFinite(q.disp)?` · dispersão ${q.disp.toFixed(2)}°`:'');const b=$('ar6Bubble');if(b&&lv){const x=Math.max(-1,Math.min(1,lv.nx))*90,y=Math.max(-1,Math.min(1,-lv.ny))*90;b.style.transform=`translate(calc(-50% + ${x}px),calc(-50% + ${y}px))`}}
function recent(){try{return JSON.parse(localStorage.getItem('ita_arandu_compass_recent_r6')||'[]')}catch{return[]}}
function saveRecent(r){const a=recent();a.unshift(r);localStorage.setItem('ita_arandu_compass_recent_r6',JSON.stringify(a.slice(0,20)));renderRecent()}
function renderRecent(){const h=$('ar6Recent');if(!h)return;const a=recent().slice(0,5);h.innerHTML=a.length?'<h3>Últimas medições</h3>'+a.map(r=>`<div class="ar6-recent-row"><span>${r.time}</span><span>${r.type} · ${r.dir}</span><b>${r.az.toFixed(1)}° / ${Number.isFinite(r.dip)?r.dip.toFixed(1)+'°':'—'}</b></div>`).join(''):'<div class="ar6-mini-status">Nenhuma medição salva nesta sessão do navegador.</div>'}
function fillMeasure(data){$('campoAddMedida')?.click();const card=qa('#campoMedidasLista [data-measure]').at(-1);if(!card)return false;const set=(k,v)=>{const e=card.querySelector(`[data-k="${k}"]`);if(e){e.value=v??'';e.dispatchEvent(new Event('change',{bubbles:true}))}};set('type','outro');set('direction',data.direction);set('dip',data.dip);set('method',data.method);set('instrument',data.instrument);set('precision',data.precision);return true}
function saveCompass(){const d=decl(),az=S.reference==='geo'?trueHeading():S.heading;if(!Number.isFinite(az)){alert('Ative os sensores antes de salvar.');return}if(S.reference==='geo'&&!Number.isFinite(d)){alert('Informe a declinação antes de usar a referência geográfica.');return}const q=qCompass(),type=$('ar6Element')?.value||'Plano',structure=$('ar6Structure')?.value?.trim()||'',obs=$('ar6Obs')?.value?.trim()||'';const rec={ts:new Date().toISOString(),time:new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'}),type,structure,obs,reference:S.reference,az,azMag:S.heading,declination:d,azGeo:trueHeading(),dip:S.tilt,dir:dir8(az),dispersion:q.disp,absolute:S.absolute,source:S.source,gps:S.gps,declination_source:$('ar6DeclSource')?.value?.trim()||null};saveRecent(rec);const ok=fillMeasure({direction:az,dip:S.tilt,method:S.reference==='geo'?'bussola_sensor_declinação_informada':'bussola_sensor_magnética',instrument:'ITA ARANDU · DeviceOrientationEvent',precision:`referencia=${S.reference}; absoluta=${S.absolute}; dispersao=${Number.isFinite(q.disp)?q.disp.toFixed(2):'NA'}°; declinacao=${Number.isFinite(d)?d:'NA'}°`});$('bussolaStatus').textContent=ok?'Medição salva também no Caderno de Campo.':'Medição salva localmente. Abra uma estação do Campo para vincular ao Caderno.'}
function saveLevel(){if(!Number.isFinite(S.tilt)){alert('Ative os sensores antes de salvar.');return}const q=qLevel(),ok=fillMeasure({direction:'',dip:S.tilt,method:'nivel_digital_plano_tela',instrument:'ITA ARANDU · DeviceOrientationEvent',precision:`dispersao=${Number.isFinite(q.disp)?q.disp.toFixed(2):'NA'}°; qualidade=${q.label}`});$('nivelStatus').textContent=ok?'Inclinação adicionada ao Caderno de Campo.':'Leitura pronta. Abra uma estação do Campo para vincular.'}
function locate(){if(!navigator.geolocation){$('ar6GpsText').textContent='Geolocalização indisponível neste navegador.';return} $('ar6GpsText').textContent='Obtendo localização…';navigator.geolocation.getCurrentPosition(p=>{S.gps={lat:p.coords.latitude,lon:p.coords.longitude,altitude:p.coords.altitude,accuracy:p.coords.accuracy};$('ar6GpsShort').textContent=`${S.gps.lat.toFixed(5)}, ${S.gps.lon.toFixed(5)}`;$('ar6GpsText').textContent=`Lat ${S.gps.lat.toFixed(6)} · Lon ${S.gps.lon.toFixed(6)} · altitude ${Number.isFinite(S.gps.altitude)?Math.round(S.gps.altitude)+' m':'—'} · precisão ${Number.isFinite(S.gps.accuracy)?'±'+Math.round(S.gps.accuracy)+' m':'—'}`},e=>$('ar6GpsText').textContent='GPS indisponível · '+e.message,{enableHighAccuracy:true,timeout:15000,maximumAge:0})}
function openTool(id){close('bussolaAranduModal');setTimeout(()=>$(id)?.click(),50)}
function wire(){replaceModals();renderRecent();$('abrirBussolaArandu')?.addEventListener('click',()=>open('bussolaAranduModal'));$('abrirNivelArandu')?.addEventListener('click',()=>open('nivelAranduModal'));qa('[data-close="bussolaAranduModal"]').forEach(b=>b.addEventListener('click',()=>close('bussolaAranduModal')));qa('[data-close="nivelAranduModal"]').forEach(b=>b.addEventListener('click',()=>close('nivelAranduModal')));qa('[data-tool-action="bussola"]').forEach(b=>b.addEventListener('click',()=>open('bussolaAranduModal')));qa('[data-tool-action="nivel"]').forEach(b=>b.addEventListener('click',()=>open('nivelAranduModal')));$('ar6Calibrate')?.addEventListener('click',startSensors);$('ar6LevelStart')?.addEventListener('click',startSensors);$('ar6Lock')?.addEventListener('click',e=>{S.frozen=!S.frozen;e.currentTarget.textContent=S.frozen?'▶ Destravar':'▣ Travar'});$('ar6More')?.addEventListener('click',()=>{$('ar6Data').open=true;$('ar6Data').scrollIntoView({behavior:'smooth',block:'start'})});$('ar6Save')?.addEventListener('click',saveCompass);$('ar6LevelSave')?.addEventListener('click',saveLevel);$('ar6Decl')?.addEventListener('input',renderCompass);$('ar6Gps')?.addEventListener('click',locate);$('ar6Photo')?.addEventListener('click',()=>{close('bussolaAranduModal');setTimeout(()=>{if($('geocameraModal')){open('geocameraModal')}else window.ITA_FERRAMENTAS?.actions?.geocamera?.()},60)});$('ar6Stereo')?.addEventListener('click',()=>openTool('abrirEstereogramaArandu'));$('ar6Rose')?.addEventListener('click',()=>openTool('openRoseDiagram'));qa('[data-ar6-ref]').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.ar6Ref==='geo'&&!Number.isFinite(decl())){$('ar6Science').open=true;$('ar6Science').scrollIntoView({behavior:'smooth',block:'start'});return}S.reference=b.dataset.ar6Ref;qa('[data-ar6-ref]').forEach(x=>x.classList.toggle('active',x===b));renderCompass()}));qa('[data-ar6-go]').forEach(b=>b.addEventListener('click',()=>{qa('[data-ar6-go]').forEach(x=>x.classList.toggle('active',x===b));const k=b.dataset.ar6Go;if(k==='measure')$('ar6Measure')?.scrollIntoView({behavior:'smooth',block:'center'});if(k==='data'){$('ar6Data').open=true;$('ar6Data').scrollIntoView({behavior:'smooth',block:'start'})}if(k==='analysis'){$('ar6Analysis').open=true;$('ar6Analysis').scrollIntoView({behavior:'smooth',block:'start'})}if(k==='science'){$('ar6Science').open=true;$('ar6Science').scrollIntoView({behavior:'smooth',block:'start'})}}));$('ar6Element')?.addEventListener('change',e=>$('ar6StationSummary').textContent=e.target.value);$('ar6LevelZero')?.addEventListener('click',()=>{S.levelSamples=[];$('nivelStatus').textContent='Referência de estabilidade reiniciada. Mantenha o aparelho imóvel para nova série.'});$('ar6LevelScience')?.addEventListener('click',()=>{});renderCompass()}
function init(){setTimeout(wire,0)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
window.ITA_BUSSOLA_R6={version:'6.0',startSensors,open:()=>open('bussolaAranduModal'),openLevel:()=>open('nivelAranduModal')};
})();
